export const graiAbi = [
  {
    type: 'function',
    name: 'mint',
    stateMutability: 'payable',
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: 'graiOut', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'burn',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'graiAmount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'payable',
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'lock', type: 'bool' },
    ],
    outputs: [
      { name: 'graiOut', type: 'uint256' },
      { name: 'depositValue', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'totalSupply',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalValue',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getAssets',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        type: 'tuple[]',
        components: [
          { name: 'asset', type: 'address' },
          { name: 'startTime', type: 'uint48' },
          { name: 'period', type: 'uint32' },
          { name: 'listingPriceDecimals', type: 'uint8' },
          { name: 'listingPrice', type: 'uint256' },
          { name: 'remaining', type: 'uint256' },
          { name: 'initial', type: 'uint256' },
          { name: 'maxPayment', type: 'uint256' },
          { name: 'minPayment', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getVaultsData',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        type: 'tuple[]',
        components: [
          { name: 'asset', type: 'address' },
          { name: 'seniorBalance', type: 'uint256' },
          { name: 'juniorBalance', type: 'uint256' },
          { name: 'activeAmount', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'assets',
    stateMutability: 'view',
    inputs: [{ name: 'asset', type: 'address' }],
    outputs: [
      { name: 'asset_', type: 'address' },
      { name: 'id', type: 'uint32' },
      { name: 'paused', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'vote',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'graiAmount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'bribe',
    stateMutability: 'payable',
    inputs: [
      { name: 'voter', type: 'address' },
      { name: 'graiAmount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'previewBribe',
    stateMutability: 'view',
    inputs: [
      { name: 'voter', type: 'address' },
      { name: 'graiAmount', type: 'uint256' },
    ],
    outputs: [
      { name: 'bribeAmount', type: 'uint256' },
      { name: 'premium', type: 'uint256' },
      { name: 'discount', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'votes',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'votedAt', type: 'uint48' },
      { name: 'id', type: 'uint32' },
      { name: 'rewardDebt', type: 'uint256' },
      { name: 'claimableReward', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'escrows',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [
      { name: 'account_', type: 'address' },
      { name: 'lockerId', type: 'uint32' },
      { name: 'amount', type: 'uint256' },
      { name: 'voted', type: 'uint256' },
      { name: 'lockedAt', type: 'uint48' },
      { name: 'votedAt', type: 'uint48' },
      { name: 'voterId', type: 'uint32' },
    ],
  },
  {
    type: 'function',
    name: 'getVoters',
    stateMutability: 'view',
    inputs: [
      { name: 'fromId', type: 'uint256' },
      { name: 'toId', type: 'uint256' },
    ],
    outputs: [
      {
        type: 'tuple[]',
        components: [
          { name: 'account', type: 'address' },
          { name: 'lockerId', type: 'uint32' },
          { name: 'amount', type: 'uint256' },
          { name: 'voted', type: 'uint256' },
          { name: 'lockedAt', type: 'uint48' },
          { name: 'votedAt', type: 'uint48' },
          { name: 'voterId', type: 'uint32' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'totalVoted',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalLocked',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'hasQuorum',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'liquidation',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'bribeAsset',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'settlementAsset',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'config',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'buybackCutBps', type: 'uint16' },
      { name: 'dividendCutBps', type: 'uint16' },
      { name: 'treasuryCutBps', type: 'uint16' },
      { name: 'bribePremiumBps', type: 'uint16' },
      { name: 'quorumBps', type: 'uint16' },
      { name: 'unlockFeeBps', type: 'uint16' },
      { name: 'buybackPeriod', type: 'uint32' },
      { name: 'liquidationPeriod', type: 'uint32' },
      { name: 'redeemPeriod', type: 'uint32' },
      { name: 'unlockPenaltyPeriod', type: 'uint32' },
    ],
  },
  {
    type: 'function',
    name: 'lock',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'graiAmount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unlock',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'graiAmount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'previewUnlock',
    stateMutability: 'view',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'graiAmount', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
    ],
    outputs: [
      { name: 'unlockAmount', type: 'uint256' },
      { name: 'penalty', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'previewClaim',
    stateMutability: 'view',
    inputs: [
      { name: 'holder', type: 'address' },
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: 'amount', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewClaimAll',
    stateMutability: 'view',
    inputs: [{ name: 'holder', type: 'address' }],
    outputs: [
      { name: 'assetOuts', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
    ],
  },
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'holder', type: 'address' },
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: 'claimed', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimAll',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'holder', type: 'address' }],
    outputs: [],
  },
] as const

export const priceOracleAbi = [
  {
    type: 'function',
    name: 'getPrice',
    stateMutability: 'view',
    inputs: [{ name: 'asset', type: 'address' }],
    outputs: [
      { name: 'price', type: 'uint256' },
      { name: 'priceDecimals', type: 'uint8' },
    ],
  },
] as const
