export const grsAbi = [
  { type: 'error', name: 'CapExceeded', inputs: [] },
  { type: 'error', name: 'InvalidRecipient', inputs: [] },
  { type: 'error', name: 'NotHome', inputs: [] },
  { type: 'error', name: 'NotSpoke', inputs: [] },
  { type: 'error', name: 'BucketExceeded', inputs: [] },
  { type: 'error', name: 'ProprietorGated', inputs: [] },
  { type: 'error', name: 'InvalidSchedule', inputs: [] },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
  { type: 'error', name: 'NothingToRelease', inputs: [] },
  { type: 'error', name: 'UnknownVesting', inputs: [] },
  { type: 'error', name: 'InstantNotVest', inputs: [] },
  { type: 'error', name: 'SaleClosed', inputs: [] },
  { type: 'error', name: 'SaleExceeded', inputs: [] },
  { type: 'error', name: 'InvalidPayment', inputs: [] },
  { type: 'error', name: 'PaymentFailed', inputs: [] },
  { type: 'error', name: 'UnknownSale', inputs: [] },
  {
    type: 'function',
    name: 'home',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'MAX_SUPPLY',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'remaining',
    stateMutability: 'view',
    inputs: [{ name: 'bucket', type: 'uint8' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'saleCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getSales',
    stateMutability: 'view',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      {
        name: 'listed',
        type: 'tuple[]',
        components: [
          { name: 'asset', type: 'bytes32' },
          { name: 'assetAmount', type: 'uint256' },
          { name: 'grsAmount', type: 'uint256' },
          { name: 'recipient', type: 'bytes32' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'previewBuy',
    stateMutability: 'view',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: 'cost', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'buy',
    stateMutability: 'payable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
      { name: 'to', type: 'address' },
    ],
    outputs: [{ name: 'cost', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'vestingCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getVestings',
    stateMutability: 'view',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      {
        name: 'listed',
        type: 'tuple[]',
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'bucket', type: 'uint8' },
          { name: 'funder', type: 'address' },
          { name: 'beneficiary', type: 'address' },
          { name: 'allocation', type: 'uint256' },
          { name: 'released', type: 'uint256' },
          { name: 'start', type: 'uint64' },
          { name: 'cliffEnd', type: 'uint64' },
          { name: 'end', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'releasable',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'release',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'vest',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'start', type: 'uint64' },
      { name: 'cliffSeconds', type: 'uint64' },
      { name: 'durationSeconds', type: 'uint64' },
    ],
    outputs: [{ name: 'vestingId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getAllocations',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        name: 'listed',
        type: 'tuple[]',
        components: [
          { name: 'bucket', type: 'uint8' },
          { name: 'cap', type: 'uint256' },
          { name: 'spent', type: 'uint256' },
          { name: 'remaining', type: 'uint256' },
          { name: 'gate', type: 'uint8' },
          { name: 'cliffMonths', type: 'uint32' },
          { name: 'linearMonths', type: 'uint32' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getPeers',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        name: 'listed',
        type: 'tuple[]',
        components: [
          { name: 'eid', type: 'uint32' },
          { name: 'peer', type: 'bytes32' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'quoteBridge',
    stateMutability: 'view',
    inputs: [
      { name: 'dstEid', type: 'uint32' },
      { name: 'to', type: 'bytes32' },
      { name: 'amountLD', type: 'uint256' },
    ],
    outputs: [{ name: 'nativeFee', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'quoteSale',
    stateMutability: 'view',
    inputs: [
      { name: 'asset', type: 'bytes32' },
      { name: 'assetAmount', type: 'uint256' },
      { name: 'grsAmount', type: 'uint256' },
      { name: 'recipient', type: 'bytes32' },
      { name: 'dstEid', type: 'uint32' },
    ],
    outputs: [{ name: 'nativeFee', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'sale',
    stateMutability: 'payable',
    inputs: [
      { name: 'asset', type: 'bytes32' },
      { name: 'assetAmount', type: 'uint256' },
      { name: 'grsAmount', type: 'uint256' },
      { name: 'recipient', type: 'bytes32' },
      { name: 'dstEid', type: 'uint32' },
    ],
    outputs: [{ name: 'id', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'bridge',
    stateMutability: 'payable',
    inputs: [
      { name: 'dstEid', type: 'uint32' },
      { name: 'to', type: 'bytes32' },
      { name: 'amountLD', type: 'uint256' },
    ],
    outputs: [],
  },
] as const
